# Generated by Django 5.1.2 on 2024-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender_category', models.CharField(choices=[('male', 'Male Wear'), ('female', 'Female Wear')], max_length=6)),
                ('item_category', models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('accessory', 'Accessory')], max_length=20)),
                ('image', models.ImageField(upload_to='clothes_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
